project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  twitter-card: true
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: main_pjt.qmd
        text: Projects
      - href: other_pjt.qmd
        text: Other Projects
      - href: "https://drive.google.com/file/d/1frZ_-wxQyCSDJU8Vj-oJQGpB0WHXVE0p/view?usp=share_link"
        text: CV
      - icon: github
        href: https://github.com/akins11
        aria-label: GitHub
    background: "#FCFCFC"
    foreground: dark

format:
  html:
    theme: 
      - Zephyr
      - custom.scss
    css: styles.css
    toc: false
    page-layout: custom

editor: source

